from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")

model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neox-20b").half().cuda().eval()

prompt = """

The Company’s services also face substantial competition, including from companies that have significant resources and experience and have established service offerings with large customer bases. The Company competes with business models that provide content to users for free. The Company also competes with illegitimate means to obtain third-party digital content and applications.
The Company’s future financial condition and operating results depend on the Company’s ability to continue to develop and offer new innovative products and services in each of the markets in which it competes. The Company believes it offers superior innovation and integration of the entire solution including the hardware (iOS devices, Mac, Apple Watch and Apple TV), software (iOS, macOS, watchOS and tvOS), online services and distribution of digital content and applications (Digital Content and Services). Some of the Company’s current and potential competitors have substantial resources and may be able to provide such products and services at little or no profit or even at a loss to compete with the Company’s offerings.
Supply of Components
Although most components essential to the Company’s business are generally available from multiple sources, certain components are currently obtained from single or limited sources. In addition, the Company competes for various components with other participants in the markets for mobile communication and media devices and personal computers. Therefore, many components used by the Company, including those that are available from multiple sources, are at times subject to industry-wide shortage and significant commodity pricing fluctuations that could materially adversely affect the Company’s financial condition and operating results.
The Company uses some custom components that are not commonly used by its competitors, and new products introduced by the Company often utilize custom components available from only one source. When a component or product uses new technologies, initial capacity constraints may exist until the suppliers’ yields have matured or manufacturing capacity has increased. If the Company’s supply of components for a new or existing product were delayed or constrained, or if an outsourcing partner delayed shipments of completed products to the Company, the Company’s financial condition and operating results could be materially adversely affected. The Company’s business and financial performance could also be materially adversely affected depending on the time required to obtain sufficient quantities from the original source, or to identify and obtain sufficient quantities from an alternative source. Continued availability of these components at acceptable prices, or at all, may be affected if suppliers decide to concentrate on the production of common components instead of components customized to meet the Company’s requirements.
The Company has entered into agreements for the supply of many components; however, there can be no guarantee that the Company will be able to extend or renew these agreements on similar terms, or at all. Therefore, the Company remains subject to significant risks of supply shortages and price increases that could materially adversely affect its financial condition and operating results.
Substantially all of the Company’s hardware products are manufactured by outsourcing partners that are located primarily in Asia, with some Mac computers manufactured in the U.S. and Ireland. A significant concentration of this manufacturing is currently performed by a small number of outsourcing partners, often in single locations. Certain of these outsourcing partners are single-sourced suppliers of components and manufacturers for many of the Company’s products. Although the Company works closely with its outsourcing partners on manufacturing schedules, the Company’s financial condition and operating results could be materially adversely affected if its outsourcing partners were unable to meet their production commitments. The Company’s manufacturing purchase obligations typically cover its requirements for periods up to 150 days.
Research and Development
Because the industries in which the Company competes are characterized by rapid technological advances, the Company’s ability to compete successfully depends heavily upon its ability to ensure a continual and timely flow of competitive products, services and technologies to the marketplace. The Company continues to develop new technologies to enhance existing products and services, and to expand the range of its offerings through R&D, licensing of intellectual property and acquisition of third-party businesses and technology.
Intellectual Property
The Company currently holds a broad collection of intellectual property rights relating to certain aspects of its hardware devices, accessories, software and services. This includes patents, copyrights, trademarks, service marks, trade dress and other forms of intellectual property rights in the U.S. and a number of foreign countries. Although the Company believes the ownership of such intellectual property rights is an important factor in its business and that its success does depend in part on such ownership, the Company relies primarily on the innovative skills, technical competence and marketing abilities of its personnel.

Task
You are asked to come up with a set of 20 diverse task instructions. (1) These task instructions will be given to to you and  we will evaluate you on completing the diverse instructions. (2) Do not repeat the verb for each instruction, and keep the langauge and type of the instruction diverse.  (3) You should generate an appropriate input to the instruction, with  a specific realistic example, and not placeholders. (4) The input should provide substantial content to make the instruction challenging. (5) Where there is no input,simply put "<noinput>" in the input field. The output should be an appropriate response to the instruction and the input. 

List of 20 diverse task instructions, each with an instruction, input and output:
"""

print (tokenizer.batch_decode(model.generate(**tokenizer(prompt, return_tensors='pt').to(device),   no_repeat_ngram_size=4,  repetition_penalty=1.01, max_length=2048,min_length=512),))
